name: Build and deploy ASP.Net Core app to an Azure Web App
on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '6' 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Check out repo      
      - uses: actions/checkout@v2
  
      # Setup .NET core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and publish
      - name: Build and publish with dotnet
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './published-app'

      # Publish artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: './published-app'

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: build-and-publish
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: published-app
          path: './published-app'
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: github-dev
          publish-profile: $
          package: './published-app'


  deploy-prod:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: [build-and-publish, deploy-dev]
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: published-app
          path: './published-app'
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: github-prod
          publish-profile: $
          package: './published-app'
